### ISSUE TITLE
design: Figure out how we want to spawn our NPCs

### ISSUE THREAD

**Issue by edisontim** [The-Overlore/eternum#21]
Atm I just added a `Spawn villager` button back in the UI but this has to go for the final integration

**Comment by cwastche** [comment]
![spawn_npc_design](https://github.com/The-Overlore/eternum/assets/80072466/269f5d66-cae4-4c61-b098-e9e42a954023)

**Comment by edisontim** [comment]
Closed by #48 and previously merged PRs
